AudiusProject/audius-docker-compose

discovery-provider/docker-compose.yml
discovery-provider/env

Reverts AudiusProject/audius-docker-compose#1

Revert "Add elasticsearch container"

---

discovery-provider/docker-compose.yml
discovery-provider/env

Reverts AudiusProject/audius-docker-compose#2

Revert "Revert "Add elasticsearch container""

---

audius-cli
creator-node/docker-compose.yml
discovery-provider/docker-compose.yml
setup.sh

Fixes in this PR
- Check disk storage and display if it meets min requirements
- Randomize auto upgrade cron to a random minute within an hour. Otherwise every node would upgrade at the same time and that's probably not good for the network
- Enable auto upgrade by default
- Update phrase for seed job prompt

Final audius-cli fixes and setup prompt tweaks

---

ADVANCED_SETUP.md
README.md
creator-node/prod.env
creator-node/stage.env

Some more refactoring for README, mostly to move explanations for env vars to main README from advanced section

README updates + small tweaks

---

creator-node/prod.env
creator-node/stage.env
discovery-provider/prod.env
discovery-provider/stage.env

Sister PR to https://github.com/AudiusProject/audius-protocol/pull/3124

[INF-93] disable rsyslog in favor of logspout

---

creator-node/stage.env

Pairs with https://github.com/AudiusProject/audius-protocol/pull/3223

CON-200 Add snapbackMaxLastSuccessfulRunDelayMs

---

README.md
sp-utilities/README.md
sp-utilities/claim/README.md
sp-utilities/claim/claim.js
sp-utilities/creator-node/README.md
sp-utilities/creator-node/apiSigning.js
sp-utilities/creator-node/delistContent.js
sp-utilities/creator-node/healthChecks.js
sp-utilities/discovery-provider/README.md
sp-utilities/discovery-provider/healthChecks.js
sp-utilities/package-lock.json
sp-utilities/package.json

Add [sp-utilities](https://github.com/AudiusProject/audius-k8s-manifests/tree/master/sp-utilities) from audius-k8-manifests to audius-docker-compose.

Add SP Utilities folder to compose + add section in README

---

setup.sh

Add checks to verify Ubuntu OS and kernel versions. This is for better standardization across VMs in different cloud providers

Add checks for Ubuntu OS and kernel versions

---

creator-node/prod.env
creator-node/stage.env

Change env var to run 1 state machine job every minute instead of 3 jobs every minute.

Lower state monitoring job frequency

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml
identity-service/docker-compose.yml

https://github.com/AudiusProject/audius-protocol/commit/76fe3e99b84daa0563306698977e874b3e59f64a

release-v0.3.63 with sql trigger fix

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml
identity-service/docker-compose.yml

Reverts AudiusProject/audius-docker-compose#47

Revert "release-v0.3.63 with sql trigger fix"

---

README.md
common-services.yml
discovery-provider/prod.env
discovery-provider/stage.env

Reverts AudiusProject/audius-docker-compose#50

Revert "Make audius_discprov_url required and add blurb about logging"

---

audius-cli

[INF-225][INF-232] Log settings

---

creator-node/stage.env

Already live on CN10 https://creatornode10.staging.audius.co/health/bull/queue/monitor-state-queue
http://grafana.audius.co/d/qyiCv3WVz/audius-content-node-profiling?orgId=1&var-env=stage&var-host=creatornode10.staging.audius.co&var-path=All&var-method=All&from=1663011376153&to=1663022176153

Increase stage CN snapbackUsersPerJob from 1k to 2k

---

creator-node/prod.env

Sets:
snapbackHighestReconfigMode=PRIMARY_AND_OR_SECONDARIES
snapbackUsersPerJob=2000

Enable prod primary reconfig + 2s snapbackUsersPerJob

---

audius-cli

Run nethermind chain with DN by default

---

creator-node/stage.env

So that we can test the premium content on stage

Enable premium content on stage

---

creator-node/docker-compose.yml

https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.67-patch-cn

Change CN tag only to protocol v0.3.67-patch-cn

---

creator-node/docker-compose.yml

pointer to head of https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.68

CN track upload hotfix

---

discovery-provider/docker-compose.yml

Gets 28a19fb9aa5f99d286831cbcb84b1f25fc6da19c
from https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.68

Unlisted track upload hotfix

---

creator-node/prod.env

Enable prod CN content cache

---

creator-node/docker-compose.yml
creator-node/prod.env

Tag commit: https://github.com/AudiusProject/audius-protocol/commit/c5c45fb68ba476aa951c5e954f2884f408247d13
Tag branch: https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.68-foundation-cn-v2/creator-node

CN Prod - change CN tag & set maxUpdateReplicaSetJobConcurrency = 0

---

creator-node/stage.env

Disable reconfigModePrimaryOnly for staging CN

Disable reconfigModePrimaryOnly for staging CN

---

creator-node/prod.env
creator-node/stage.env

Associated PR: https://github.com/AudiusProject/audius-protocol/pull/4198

CN Disk envvar cleanup STAGE

---

creator-node/docker-compose.yml

commit hash is https://github.com/AudiusProject/audius-protocol/commits/a752d1dcd5522a0dd252cdfa823bec8ab5602157
from this release branch https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.69-cn-patch
identical to code running on foundation nodes

update cn tag to release-v0.3.69-cn-patch

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

Changes tag to latest head of https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.70, with 2 notable changes:
https://github.com/AudiusProject/audius-protocol/pull/4371
https://github.com/AudiusProject/audius-protocol/pull/4352

Hotfix db leak in backfill indexers

---

discovery-provider/seed.sh

Update dump/restore owner and privileges

Update dump/restore owner and privileges

---

discovery-provider/prod.env

Ship dummy counter env to trigger restart

---

.gitignore
sp-utilities/creator-node/README.md

Update sp utils README

---

discovery-provider/docker-compose.yml

https://github.com/AudiusProject/audius-protocol/tree/release-v0.3.72

Update backfill migration in 0.3.72

---

audius-cli

https://github.com/AudiusProject/audius-protocol/pull/4434

Add commit as env var

---

identity-service/prod.env
identity-service/stage.env

Updates general admission addresses for identity

Update general admission env vars

---

creator-node/docker-compose.yml
creator-node/stage.env

Compare CN tag against head commit of https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.73-patch-0.3.72
5a1c1526a6ed8469cdfc8d38da0b8e14113e12eb

CN release-v0.3.73-patch-v0.3.72

---

discovery-provider/docker-compose.yml

collection uploading on stage works

Hotfix remove caching for unclaimed ID

---

discovery-provider/docker-compose.yml

hotfix handle lowercase

---

discovery-provider/docker-compose.yml

https://github.com/AudiusProject/audius-protocol/pull/4546

Update discovery for skip missing users fix

---

discovery-provider/docker-compose.yml

see https://github.com/AudiusProject/audius-protocol/pull/4525

update nethermind port config

---

discovery-provider/docker-compose.yml

Adds logic to handle subscription reverts:
https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.72

hotfix for subscription revert logic

---

creator-node/prod.env
creator-node/stage.env

do not merge until after 0.3.74 release commit

0.3.74 release changes - enable CN reconfig, reduce CN dbConnPool

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

rename comms container

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

Add logging limits to nats containers

Add logging limits

---

sp-utilities/claim/README.md

Add newline

---

discovery-provider/docker-compose.yml

Contains changes for indexer for playlist bug
Branch https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.75

Update dn patch of v0.3.75

---

audius-cli

Removes system prune prompt
Tested via `audius-cli upgrade raymondjacobson-patch-2`

Pass --force to system prune

---

README.md

Update README to include upgrade instructions

---

README.md

Add instructions to set override path

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

update comms / nats / storage version

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

ignore nats in logspout

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

Need to expose default `prod.env` for when postgres is running in adjacent docker...

Add default prod.env file to comms container.

---

creator-node/docker-compose.yml

https://github.com/AudiusProject/audius-protocol/pull/4684
Includes patch to the method /segment_to_cid

Update backend tag to include /segment_to_cid fix

---

discovery-provider/docker-compose.yml

Cherry pick [PAY-915] to improve stream_cid performance

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

update comms version

---

discovery-provider/chain/prod_spec_template.json

Reset chain to 1056802 (0x102022). Prod nodes are already on this network ID so SPs will join with auto upgrade. Then we'll manually add signers and observe.

Reset chain to 1056802

---

discovery-provider/chain/prod_spec_template.json

Reset chain to 566b

---

creator-node/docker-compose.yml
creator-node/stage.env
discovery-provider/docker-compose.yml
discovery-provider/stage.env

The `storage` and `nats` containers are missing env files for prod.env and stage.env, so this fixes that.

Add stage and prod env files to nats and storage

---

discovery-provider/docker-compose.yml

PLAT-748: use latest nethermind image

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

disable NATS in prod unless explicitly enabled.
https://github.com/AudiusProject/audius-protocol/pull/4891

Update nats / storage / comms.

---

discovery-provider/docker-compose.yml

Pin nethermind to 1.17.0

---

discovery-provider/docker-compose.yml

Hotfix removing prometheus

---

discovery-provider/docker-compose.yml

Update comms image

---

discovery-provider/docker-compose.yml

Reference release branch https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.78

Update to latest v0.3.78 discovery

---

sp-utilities/discovery-provider/healthChecks.js

Very trivial pr, just adds a few msgs so I could get the error msg from the terminal without going back to the code.
I added it to my local but thought I'd spin up a pr if its useful, feel free to close if not!

[Trivial] Add a few msgs to the sp utilties

---

audius-cli
discovery-provider/docker-compose.notifications.yml
discovery-provider/docker-compose.yml

Manually tested to deploy the notifications service

Notifications cli

---

discovery-provider/chain/prod_spec_template.json

ACDC migration chain reset again

---

discovery-provider/docker-compose.yml

https://github.com/AudiusProject/audius-protocol/commits/577cbd11acb659ac0d819eb14c9c12cc964bdd83

Hotfix drop constraints on blocks

---

discovery-provider/docker-compose.yml

A few updates to speed up reverting and stop POA indexing
https://github.com/AudiusProject/audius-protocol/tree/release-v0.3.78

Hotfix revert by number + stop POA indexing

---

discovery-provider/docker-compose.yml

Hotfix es-indexer query for index tracks
Commit: https://github.com/AudiusProject/audius-protocol/commit/d04bb58fd72ac6057f24234cc855c203ab046c34

Hot fix es-indexer is_available

---

discovery-provider/docker-compose.yml

bypass notification txs

---

creator-node/docker-compose.yml

Network adoption of 0.3.80 proving difficult.

Revert to 0.3.78 on content nodes

---

audius-cli
discovery-provider/docker-compose.notifications.yml

Adds health check to discovery provider notifications

Discovery notifs health

---

creator-node/docker-compose.yml

Update content node SHA to 0.3.80

---

discovery-provider/docker-compose.yml

Hotfix re-enable track trigger

---

discovery-provider/docker-compose.yml

update comms to use correct POA gateway

---

audius-cli

Add until to prune

---

audius-cli

Foiled by @stereosteve 
🙇 
Tested on stage node

Missing --filter before until

---

install.sh

Allows switching default branch to `dev`

Update install.sh script to pull main

---

audius-cli

[INF-385] Move to 2w cleanup

---

audius-cli

2w though supported by the go format does not work for docker

Switch to 2 weeks in hours

---

audius-cli

Cherry pick until fix

---

README.md

Touch readme

---

discovery-provider/docker-compose.yml

adds a nethermind image that Audius maintains which includes curl and jq

custom nethermind image and health check

---

creator-node/docker-compose.yml
creator-node/prod.env

mediorum: tag image, run on subset of hosts

---

creator-node/docker-compose.yml

Change: https://github.com/AudiusProject/audius-protocol/tree/release-v0.3.82

Update content node to 47ed0af

---

.gitignore
discovery-provider/docker-compose.yml

Get rid of noise

---

utilities/discovery-provider/healthChecks.js
utilities/package-lock.json
utilities/package.json

also: https://github.com/AudiusProject/audius-protocol/pull/5102

Add websocket connection test

---

README.md

Add proxy config advice
https://github.com/AudiusProject/audius-docker-compose/tree/raymondjacobson-patch-2#proxy-configuration

Add proxy config to README

---

setup.sh

Add identity env

---

creator-node/docker-compose.yml

Bump mediorum tag

---

discovery-provider/docker-compose.yml

Nodes seem flaky atm w restarting. Going to revert for now.

Revert autoheal chain container

---

discovery-provider/docker-compose.yml
discovery-provider/prod.env
discovery-provider/stage.env

Move ES indexer to indexer only

---

discovery-provider/docker-compose.yml

revert version

---

discovery-provider/chain/NLog.config
discovery-provider/chain/config.cfg
discovery-provider/docker-compose.yml

Based off 
https://github.com/NethermindEth/nethermind/blob/release/1.14.3/src/Nethermind/Nethermind.Runner/NLog.config

Disable JSON RPC logs

---

creator-node/docker-compose.yml

Updates mediorum tag to [c48a2e1c48f1cf28c329cbde3cb6d9eaa4a7c541](https://github.com/AudiusProject/audius-protocol/commit/c48a2e1c48f1cf28c329cbde3cb6d9eaa4a7c541) to test my polling functionality and Steve's cid_lookup (excluding segments) functionality on foundation nodes.

Update mediorum tag to c48a2e1c48f1cf28c329cbde3cb6d9eaa4a7c541

---

common-services.yml
creator-node/docker-compose.yml
discovery-provider/docker-compose.yml
identity-service/docker-compose.yml

* Add docker exporter
* Remove postgres RR exporter

[PLAT-917] Add docker exporter

---

discovery-provider/docker-compose.yml

Upgrade nethermind to 1.17.4 (latest without ZeroBalanceFilter)

Upgrade nethermind to 1.17.4

---

discovery-provider/docker-compose.yml

clique_propose seems to be broken on 1.17.4. works on 1.14.3 though.

Revert version for clique_propose

---

audius-cli
discovery-provider/docker-compose.yml

Prune everything when disk space is over 95%. This has occurred on a few of our nodes and is important to do now that we're pulling more images with plugins.

Prune according to disk space

---

utilities/claim/README.md
utilities/claim/claim.js

Bug introduced when eth gas station calls were fixed.

Fix getGasPrice call

---

creator-node/prod.env

Migrates all Qm CIDs. We've already migrated all on some prod nodes, and we've migrated 1 iteration on SPs.

Run unlimited Qm CID migrations

---

discovery-provider/docker-compose.plugins.yml
discovery-provider/prod.env
discovery-provider/stage.env

adds relevant config to discprov so relay can just use that, pulls in all config in the same way that notifications does

PLAT-1176: cleanup relay

---

discovery-provider/prod.env
discovery-provider/stage.env

Makes it so better sdk/libs init can happen via plugins

Add eth token to discovery env files

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml
identity-service/docker-compose.yml

Merge dev into main, fix conflicts

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml
identity-service/docker-compose.yml

Fix merge conflicts

---

creator-node/Caddyfile
creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

fast is good
Custom docker file: https://github.com/AudiusProject/audius-protocol/pull/5926

Add caddy cache

---

discovery-provider/docker-compose.plugins.yml

sister pr: https://github.com/AudiusProject/audius-protocol/pull/6048

Match plugin tags to normal tags

---

discovery-provider/docker-compose.plugins.yml

No separate notifs env

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.plugins.yml
discovery-provider/docker-compose.yml
identity-service/docker-compose.yml

This is to soak v0.4.10 on foundation nodes before the SP deploy. I'm working on automating this.

Update to v0.4.10

---

discovery-provider/docker-compose.yml

Fixes a typo in network name for healthz container in discovery. Testing now on a discovery node...

Fix network name for healthz in discovery

---

audius-cli

No recreate chain containers to prevent restarts with higher frequency auto upgrading.

No recreate chain container

---

discovery-provider/docker-compose.yml

Fix release 4.20 foundation tag

---

discovery-provider/docker-compose.yml

Add a mem limit here to prevent a worker from taking down the whole node.

Add indexer mem limit

---

common-services.yml
creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

Counterpart of audius-protocol PR: https://github.com/AudiusProject/audius-protocol/pull/6350

[PROTO-1349] Continuous deployment for healthz

---

audius-cli
creator-node/Caddyfile
creator-node/docker-compose.plugins.yml
discovery-provider/docker-compose.plugins.yml

Support plugins in CNs and add dashboard a plugin.
Tested on stage CN 12:
`audius-cli register-plugin creator-node dashboard`
`audius-cli print-plugins creator-node`
`audius-cli launch-plugins creator-node`
visit https://creatornode12.staging.audius.co/dashboard/

CN plugins

---

audius-cli

fix upgrade

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

Makes Content and Discovery run the `uptime` container that was added in https://github.com/AudiusProject/audius-protocol/pull/6610.

Run uptime containers

---

common-services.yml
creator-node/docker-compose.yml
discovery-provider/docker-compose.yml
identity-service/docker-compose.yml

This reverts commit 9217717759024101018f1ffb54816ac6db227088.

Revert "Remove exporter containers (#398)"

---

common-services.yml
creator-node/docker-compose.yml
discovery-provider/docker-compose.yml
identity-service/docker-compose.yml

The exporter removal https://github.com/AudiusProject/audius-docker-compose/pull/398/files#diff-39b7c35cc5bedaea98ec2d1ebe222809e5f49e11f51c73e2d96c823802319cbc was incomplete.
Creator and identity had some remnants that would break on upgrade.

Fix exporter removal

---

discovery-provider/docker-compose.yml

Merge after https://github.com/AudiusProject/audius-protocol/pull/6776 is deployed.

Compose changes for dashboard entrypoint

---

discovery-provider/stage.env

default to use AAO for relay on stage

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

Consumes changes from https://github.com/AudiusProject/audius-protocol/pull/7014.

Consume protocol dashboard stage vs prod images

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

Reverts consuming changes in protocol dashboard. See https://github.com/AudiusProject/audius-protocol/pull/7017

Revert protocol dashboard changes

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

Adds back changes from https://github.com/AudiusProject/audius-docker-compose/pull/432

Add back dashboard changes

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

Same PR as https://github.com/AudiusProject/audius-protocol/pull/7024, but it got bulldozed. The fix to prevent future bulldozing is https://github.com/AudiusProject/audius-protocol/pull/7024.

Adds back tag changes which got bulldozed

---

discovery-provider/docker-compose.yml

Updates Discovery to latest SHA. Will test on a stage node before merging.

Update DN to latest

---

audius-cli

Tests internet access from server and chain container. These logs are piped to axiom.

Test internet access from server and chain

---

discovery-provider/docker-compose.yml

Tested on the stage-audius-ddex node.

DDEX mongo container

---

audius-cli

Finishes rolling out the postgres upgrade to every Discovery Node.

[PROTO-1606] Finish postgres upgrade rollout

---

discovery-provider/docker-compose.yml

Update ddex web image

---

.gitignore
discovery-provider/docker-compose.yml

Mirrors docker compose in audius-protocol used for local dev.

Add DDEX services to docker compose

---

discovery-provider/docker-compose.yml

Add DDEX publisher service

---

discovery-provider/docker-compose.yml

Define server health check in compose. bypass_errors prevents autoheal restart loop.
https://github.com/AudiusProject/audius-protocol/compare/is-bypass-errors?expand=1

Move server healthcheck and bypass errors for autoheal

---

README.md
ddex/docker-compose.yml
install.sh
setup.sh

- Automates Mongo keyfile creation/permissions and replica set initialization
- Adds basic instructions for setting up a DDEX service

Automate Mongo init and improve ddex README

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

This reverts commit 29e15e89e203053ac54cd72bc74e8741fb3bddb1.

Revert "Allow containers via docker in docker host (#487)"

---

audius-cli

Create dn db if needed

---

audius-cli

Remove db size check

---

discovery-provider/docker-compose.yml

adds solana relay to discovery
tested locally with audius-docker-compose

PAY-2203: add solana-relay to discovery

---

discovery-provider/docker-compose.yml

right port for solana relay

---

audius-cli

Removes postgres reseeding to unblock staging. This won't go to prod until tomorrow, so it should be okay on that front because the reseeding has pretty much all but happened there.

Remove postgres reseeding

---

discovery-provider/docker-compose.yml

Closing this port breaks dn1, reopening it for now.
@alecsavvy confirmed this fixes dn1.

Reopen 5000 on openresty

---

discovery-provider/docker-compose.yml

Add crm tool

---

creator-node/stage.env

turn on stage discovery listens

---

common-services.yml

On dockerhub here:
https://hub.docker.com/layers/audius/vector/0.38.0-alpine/images/sha256-ae02c3e8efc4b44131dbe2f7b711bf945aa78bf7e0f72c98cbbbe40c2c7199e4?context=repo

Upgrade vector.dev

---

creator-node/prod.env

release discovery listens to prod

---

discovery-provider/docker-compose.yml

backfill plugin

---

discovery-provider/docker-compose.yml

run aa backfill on all nodes

---

discovery-provider/docker-compose.yml

update to latest tag

---

common-services.yml

Upgrade vector to 0.39.0
https://github.com/AudiusProject/audius-protocol/pull/9261
https://hub.docker.com/layers/audius/vector/0.39.0-alpine/images/sha256-b9196d718b1c031cb391ca8b97e08ac844bc5d5ec8d8bad72e580fa6667d144c?context=explore

Upgrade vector

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

core pull policy

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

core ports: grpc and console

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

removes the profile protection for core and runs by default

run core everywhere

---

audius-cli

tested on stage dn1 and confirmed images were pulled
tested on stage dn5 and confirmed no plugins also works

Pull discovery plugin images on upgrade

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

log rotation for core

---

utilities/claim/ERC20Splitter.json
utilities/claim/EthRewardsManager.json
utilities/claim/README.md
utilities/claim/claim.js
utilities/package-lock.json
utilities/package.json

- Wormhole sdk 2.0
- Fixed transfers
- ERC20 splitter interaction
TODO: sdk instead of libs

Improve init round

---

audius-cli

- updates the docker compose run to run with the discovery profile so the db stands up

fix seeding

---

discovery-provider/docker-compose.yml

More boilerplate! but the last of it :-)

Add staking plugin to discovery

---

utilities/claim/claim.js

- Dust check
- Wormhole is slow
TODO: move to new staking plugin on DN :)

Minor fixes to init round script

---

audius-cli

Specify dn1 specifically so that dn2 is no longer caught here

Move dn2.monophonic to new age discovery

---

discovery-provider/docker-compose.yml

Adds compose block for the the archiver service so it can be enabled on DNs if opted in.
Plus apparently bonus whitespace trimming from saving the file 😁

Add archiver service to compose file

---

discovery-provider/docker-compose.yml

This was left in during testing and not necessary anymore

Cleanup AAO port

---

discovery-provider/Caddyfile

Fix caddy when unproxy is unset

---

discovery-provider/docker-compose.yml

Remove sla-auditor

---

discovery-provider/docker-compose.yml

Verif notifs now pedalboard
