README.md
audius-cli
creator-node/docker-compose.yml
discovery-provider/docker-compose.yml
discovery-provider/seed.sh

This uses network env from a file instead of args, since we introduce the element of human error when we rely on arguments.
This allows us to set the network on startup, and use it thereafter.

Rename ENV to NETWORK and use env file over args

---

audius-cli
common-services.yml
creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

Add our custom-built logspout sidecar container for forwarding logs to Loggly.
Sister PR that builds the image can be found here: https://github.com/AudiusProject/audius-protocol/pull/3124

Use Logspout to forward logs to Loggly

---

creator-node/prod.env
creator-node/stage.env

Changes config defaults to disable snapback and enable the refactored state machine at a rate of 3 monitoring jobs per minute. Note that this change doesn't stop the manual sync queue, which snapback will continue to run regardless of the config options. See https://github.com/AudiusProject/audius-protocol/pull/3317.

Disable snapback, enable refactored state machine

---

sp-utilities/creator-node/README.md
sp-utilities/creator-node/apiSigning.js
sp-utilities/creator-node/healthChecks.js

This updates the file upload check from hearbeat to async status polling. This required some changes like the updated API signing object. The associated content node changes are at https://github.com/AudiusProject/audius-protocol/pull/3351.
This script has been used to test against a running content node.
```js
export delegatePrivateKey=...
export creatorNodeEndpoint=...
export spID=...
➜  sp-utilities git:(dm-updated-content-node-health-checks) ✗ node creator-node/healthChecks.js
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 …
```

Updated health checks for content node to consume async status polling

---

common-services.yml

According to the docker postgres [README](https://hub.docker.com/_/postgres), the only required env var is POSTGRES_PASSWORD, which we don't specify. Discovered by reading this Github issue https://github.com/sameersbn/docker-postgresql/issues/112.
Not sure if this is what's causing the db corruption / inability to connect, but we should specify this anyway.
Some other things to try
https://stackoverflow.com/a/55668376/11240376
EDIT
More docs supporting this theory. This [docker entrypoint script](https://github.com/docker-library/postgres/blob/74e51d102aede317665f2b4a9b89362135402fe7/11/alpine/docker-entrypoint.sh#L91) calls initdb and in the [docs](https://www.postgresql.org/docs/current/app-initdb.html) it says -U is the name of the superuser and it defaults to the effective user …

Explicitly specify postgres user and password in compose config

---

creator-node/prod.env
creator-node/stage.env

For rollout, write quorum should default to off on prod because we want to be able to turn write quorum on/off via Optimizely. If the write quorum env var defaults to true on prod, then we won't be able to turn it off in an emergency without waiting for SPs to update. For staging we want to test it as on by default.

Default write quorum to staging=true, prod=false

---

common-services.yml

Port 5432 is publicly accessible from outside the VM, we can lock it down by specifying only the host. Docs https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose

Lock postgres port down only to host

---

README.md
common-services.yml
discovery-provider/prod.env
discovery-provider/stage.env

Make audius_discprov_url required so both content and discovery node have a url that can be associated with the logs in the logging service. In addition add documentation about disabling logging

Make audius_discprov_url required and add blurb about logging

---

README.md
common-services.yml
discovery-provider/prod.env
discovery-provider/stage.env

Reverts AudiusProject/audius-docker-compose#51 and re-enables AudiusProject/audius-docker-compose#50

Re-enable "Make audius_discprov_url required and add blurb about logging"

---

discovery-provider/prod.env
discovery-provider/stage.env

Add entity manager contract address. 
https://www.notion.so/audiusproject/8-5-22-Deploy-EntityManager-Contract-4c0f287d717a41fbb3e15120d684782d
Contract deployed 
Prod: https://blockscout.com/poa/core/address/0x2F99338637F027CFB7494E46B49987457beCC6E3
Stage: https://blockscout.com/poa/sokol/address/0x2F99338637F027CFB7494E46B49987457beCC6E3
Note: it's the same address because it's deterministically computed https://ethereum.stackexchange.com/questions/760/how-is-the-address-of-an-ethereum-contract-computed

Add entity manager address for prod/stage DP

---

discovery-provider/docker-compose.yml

c54dc44721ad3c8352f0cec56b94002cffe9512a
is the head of release 0.3.65 (https://github.com/AudiusProject/audius-protocol/tree/release-v0.3.65)
which includes two critical fixes:
- an N+1 query fix
- a fix to remove caching that was incorrectly populating repost counts

Update discovery node to c54dc4

---

creator-node/stage.env

Will instead use value set in CN config.js (https://github.com/AudiusProject/audius-protocol/blob/master/creator-node/src/config.js#L418)
Has been working so far on staging bc literally every node has overridden this value manually 🤦

Remove stage CN snapbackHighestReconfigMode envvar

---

creator-node/prod.env
creator-node/stage.env

This PR adds the env vars for enabled opentelemetry tracing as well as for exporting data to out collector

Add OpenTelemetry Env Vars

---

creator-node/prod.env

Instead this will default to the value set in CN config.js

Unset snapbackHighestReconfigMode for prod CN

---

creator-node/prod.env

SP queues are mostly empty (on avg they have 1 active job, out of 5 possible jobs for reconfig) [see grafana panel](http://grafana.audius.co/d/3VPUdqZVz/audius-content-node-bull-queue?orgId=1&refresh=30m&from=1663282062775&to=1663303602775&var-env=prod&var-host=audius-content-1.cultur3stake.com&var-host=audius-content-10.cultur3stake.com&var-host=audius-content-11.cultur3stake.com&var-host=audius-content-12.cultur3stake.com&var-host=audius-content-13.cultur3stake.com&var-host=audius-content-14.cultur3stake.com&var-host=audius-content-15.cultur3stake.com&var-host=audius-content-16.cultur3stake.com&var-host=audius-content-17.cultur3stake.com&var-host=audius-content-18.cultur3stake.com&var-host=audius-content-2.cultur3stake.com&var-host=audius-content-3.cultur3stake.com&var-host=audius-conten …

Bump SP snapbackUsersPerJob

---

audius-cli

Handle this case gracefully:
```
INFO     [2022-09-28 19:19:10,348] >> stage-discovery-4: audius-cli health-check discovery-provider
WARNING  [2022-09-28 19:19:11,462] Traceback (most recent call last):
File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "/usr/lib/python3.8/http/client.py", line 1256, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
self.send(msg)
File …
```

INF-251 report as unhealthy for errors seen on Staging

---

discovery-provider/docker-compose.yml

The 16g shorthand doesn't work, so I typed out 16,000,000,000 which is like 15g as a default.
Hoping this might prevent the dead box scenario.

configurable mem_limit for server container

---

creator-node/stage.env

Disable premium content on stage, until we resolve why there are so may db connections caused by the premium content query.

Disable premium content on stage

---

discovery-provider/chain/config.cfg

Need free TXs for deployments
https://docs.nethermind.io/nethermind/ethereum-client/configuration/mining

Set gas price to 0 for free txs

---

creator-node/docker-compose.yml

Update content nodes to this branch https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.68-foundation-cn-v2

v0.3.68 Content node updates 2

---

discovery-provider/docker-compose.yml

The inadvertent release earlier https://github.com/AudiusProject/audius-docker-compose/commit/1b8a08e993ae7597d5fafbea8e6cc656022da717 ran a discovery migration that broke discovery nodes when the code was rolled back. This applies the migration to unblock indexing without the rest of the inadvertent release.
The release branch this is cut from is here https://github.com/AudiusProject/audius-protocol/compare/release-v0.3.68

v0.3.68 Hotfix - Discovery Node Migration fix

---

creator-node/stage.env

Enable disk prune for stage

---

creator-node/prod.env

Default mergePrimaryAndSecondaryEnabled to true

---

creator-node/docker-compose.yml

https://github.com/AudiusProject/audius-docker-compose/commit/8e38884670d715b925061aa0120df59157475513#diff-39b7c35cc5bedaea98ec2d1ebe222809e5f49e11f51c73e2d96c823802319cbcR48 changed the SHA to an old SHA and we merged that. This reverts back to the one from the release

Revert SHA back to v0.3.69 release

---

creator-node/prod.env
creator-node/stage.env

No values were changed, just re-ordered for easier management
These configs were removed since they set to same value in `config.js`:
from prod.env:
- `snapbackHighestReconfigMode`
- `contentCacheLayerEnabled`
- `reconfigModePrimaryOnly` (unset `true`)
- `mergePrimaryAndSecondaryEnabled`
from stage.env:
- `contentCacheLayerEnabled`
- `logLevel`
- `premiumContentEnabled`
- `reconfigModePrimaryOnly`

Cleanup CN configs

---

discovery-provider/docker-compose.yml

`extra_hosts` was mistakenly added to the `indexer`, not the `server` which is trying to access the `exporter_linux` container.

Swap extra hosts from indexer to server

---

creator-node/prod.env

Keep the background disk checking on, but turn deleting off

Turn off the background disk delete

---

creator-node/prod.env

Re-enable updateReplicaSet and backgroundDiskCleanupDeleteEnabled.
Do not merge until v0.3.72 is ready to go out and re-enabling reconfig is thoroughly tested

Content node config changes for v0.3.72

---

sp-utilities/creator-node/healthChecks.js

- set timeout on axios req to prevent infinite hang on unhealthy node (i was using this to check node health and noticed it never responded bc of infinite hang here)
- do fileupload check before low importance healthchecks for faster verification
- remove unused imports
I tested this locally to confirm that everything still works

SPUtilities CN Healthchecks minor improvements

---

audius-cli

Snapshot every 60 seconds so long as there has been 1 write.
This should be performant and far better than our custom persistence (especially on discovery) which persists *every* redis write for some keys to a file
https://redis.io/docs/management/persistence/
Adds `restart: always` to redis because rdb backups will let us recoup redis state if it crashes.

[PLAT-538] Enable redis persistence

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

For now comms + nats use separate tag from other containers to allow them to restart in isolation during rollout.
Eventually comms will share TAG with other containers, and NATS will be versioned with a rarely changin version number to avoid needless NATS restarts.

Version comms build with git sha.

---

audius-cli

From SP after upgrade. This should be safe to do because the new containers running should be the only ones we care about. 
Curious for your thoughts though @cheran-senthil !

Update cleanup to do system prune instead of image prune

---

audius-cli
creator-node/docker-compose.yml
discovery-provider/docker-compose.yml
identity-service/docker-compose.yml

Adds a function to `audius-cli` and makes associated changes to `set-override-path`
This let's us set an arbitrary path for `override.env`
Tested on staging

Add function to set override path

---

discovery-provider/chain/prod_spec_template.json
discovery-provider/chain/stage_spec_template.json
discovery-provider/prod.env

Make block time 1 second. Already running on stage. Prod chain is unhealthy / not used right now so this should be safe to merge.
Increment network ID to avoid cross network peering and changing network ID will trigger resetting the chain.
Prod chain stopped producing blocks. I believe because of the proposing. Disabling that for now by setting `audius_discprov_max_signers=0`.

1 second block time

---

creator-node/docker-compose.yml

Updates creator-node sha to [this cherry-picked commit](https://github.com/AudiusProject/audius-protocol/commit/9030672df38f1410677465afc4060efa0792534a) that prepends `https://` to the `creatorNodeEndpoint` env var when it's missing.
This will be ready to merge when the above linked commit is auto-deployed to staging and we confirm that staging nodes' `/config_check` endpoints display valid `creatorNodeEndpoint` and `spID`.

Prepend https:// to creatorNodeEndpoint

---

audius-cli
discovery-provider/chain/config.cfg

Add admin module for chain troubleshooting https://docs.nethermind.io/nethermind/ethereum-client/json-rpc/admin
Also I think we should pull then set env vars, this way the compose commit that's exposed in health_check is more accurate. I think the first time it auto-upgrades to a commit it'll actually still show the previous commit. I think it doesn't get corrected until the next auto-upgrade.

Add admin module

---

creator-node/stage.env
discovery-provider/stage.env

Sets `AUDIUS_IS_STAGING` to true for creator node and discovery provider. This is the get rid of the "hack" [here](https://github.com/AudiusProject/audius-protocol/blob/main/comms/discovery/config/config.go#L67-L71) so I can consolidate branching logic into a shared config. No prod changes will be needed since the code will default to false if it's not explicitly set.
Note: it would be better to not add this extra env var to discovery since discovery already has `audius_discprov_env=stage`, but it doesn't make sense for storage to set an env var with `discprov` in its name. Loading envconfig is more straightforward if the same `AUDIUS_IS_STAGING` env var is present in both comms and storage.

Add AUDIUS_IS_STAGING env var

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

The `NATS_STORE_DIR` env var is no longer needed since we now default it to the same value [here](https://github.com/AudiusProject/audius-protocol/blob/main/comms/natsd/config/config.go#L12). This is live on staging, but I'll wait to merge this until that config change reaches prod.

Remove NATS_STORE_DIR env var

---

discovery-provider/docker-compose.yml
discovery-provider/stage.env

Revert version because 17.1 is unable to clique propose for some reason...
```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Unable to cast vote: System.InvalidOperationException: Not a signer node - cannot vote\n   at Nethermind.Consensus.Clique.CliqueRpcModule.CastVote(Address signer, Boolean vote) in /src/Nethermind/Nethermind.Consensus.Clique/CliqueRpcModule.cs:line 44\n   at Nethermind.Consensus.Clique.CliqueRpcModule.clique_propose(Address signer, Boolean vote) in /src/Nethermind/Nethermind.Consensus.Clique/CliqueRpcModule.cs:line 167","data":false},"id":1
```
also adding some configs for our stage nodes just in case. they're already set in the override though.

Revert nethermind version back to 14.3

---

audius-cli
creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

adds `--remove-orphans` to docker commands to ensure `nats` and `storage` go away.

remove nats, update dms

---

audius-cli

Adds `audius-cli` commands to register, deregister, and view registered plugins. 
Installs them after autoupgrade so long as a valid `docker-compose.{plugin name}.yml` exists in the disc prov dir.
Assumes plugins only hook into discprov. This won't work for identity or storage services.

PLAT-858: register plugins on auto upgrade

---

audius-cli

Will allow chain containers to upgrade to audius/nethermind. Tested on stage DN4. Confirmed upgrade worked and it's auto restarting every few mins.

Allow recreating of chain container to allow image upgrade

---

creator-node/docker-compose.yml

Adds two env variables for port mapping.
On staging we can add this to `.env` to enable "mediorum first":
```
MEDIORUM_PORT='4000'
BACKEND_PORT='4001'
```

Mediorum port env

---

discovery-provider/docker-compose.yml

uses latest audius nethermind version, currently running on 2 out of 5 nodes on stage and healthy

PLAT-970: use latest audius nm version

---

creator-node/prod.env

Env var changes that should lower the strain on Discovery's db - calls to `/v1/full/users/content_node/all` happen less frequently and with a lower batch size. Will also cause fewer replica set updates to happen.

Make CN check 500 users per 90s instead of 2000 users per minute

---

audius-cli
discovery-provider/chain/config.cfg
discovery-provider/docker-compose.yml

Auto restart was removed because it would continuously restart because of block production config. With block production removed from health, non signers will be considered healthy and chain will restart when it stops processing blocks.
Tested on stage.

Add chain auto restart and remove block production from health

---

identity-service/prod.env
identity-service/stage.env

Chain ID is needed for wallet recovery in identity https://github.com/AudiusProject/audius-protocol/pull/5420/files#diff-87ec6276585346c98b198f873a683f510d0d3e17d2fc8accad6192ff41a13f5aR198
Chain ID comes from the Discovery health check https://discoveryprovider.audius.co/health_check

Add chain ID to identity env

---

creator-node/prod.env
creator-node/stage.env

Disables the queues that handle recurring syncs and replica set updates. Leaves manual syncs alone because v1 signups rely on these to sync metadata from primary->secondaries. Note that I accidentally pushed directly to dev and reverted after.

[CON-770] Turn off state machine

---

audius-cli

No need to recreate chain container since we're settling on this version. Right now, the chain container is recreating every hour with auto-upgrade. This will just leave it running.

Remove force recreate of chain

---

creator-node/Caddyfile
creator-node/docker-compose.yml
discovery-provider/Caddyfile
discovery-provider/docker-compose.yml

Adds caddy container to make it easy to do letsencrypt (if not using cloudflare proxy) or self signed cert (if using cloudflare proxy).
This can remove the need for external ssl termination in a load balancer or similar.
Using `audius-cli`
```sh
audius-cli set-config creator-node HOST_NAME 'my.coolhost.com'
audius-cli set-config creator-node CADDY_TLS 'tls internal'
```
or if editing override directly:
```sh
HOST_NAME='my.coolhost.com'
CADDY_TLS='tls internal'
```

caddy reverse proxy setup

---

creator-node/docker-compose.yml

Mediorum needs to be able to delete from the legacy creator node's filesystem in order to migrate Qm CIDs to the CDK/v2 bucket.

Allow mediorum to write legacy fs

---

utilities/creator-node/healthChecks.js

Uses the `allow_unregistered` queryparam from https://github.com/AudiusProject/audius-protocol/pull/5741

Return 200 for unregistered nodes in health check

---

creator-node/prod.env

Postgres query insights are showing the crudr sweep query hanging, presumably because the ops table is now ~10M rows. This pauses the migration until we can sort that out.

Pause Qm CID migration

---

common-services.yml

It seems to run stably, but hard to gather enough data on a sandbox discovery node 
http://34.72.186.34:5000/health_check
Looking at RDS/CloudSQL, this value is set to >25% total system memory. Setting to 2GB sets it to 12.5% of our min specs, which I think is safe. ES being the biggest memory hog uses ~15% ... and content nodes are very quiet on memory usage.

Update common postgres shared_buffers from 512mb to 2gb

---

discovery-provider/docker-compose.yml

server is 500'ing because trusted notifier delists are behind. for some reason the indexer health check depends on the server being up. delists can't progress unless the indexer is up. and we are stuck.
affected nodes:
- w3coins
- culturestake 7
- hashbeam
- stuffisup

fix indexer / server failure cycle

---

utilities/README.md
utilities/creator-node/apiSigning.js
utilities/creator-node/delistContent/hashIds.js
utilities/creator-node/delistContent/index.js
utilities/package.json

Nodes can delist and undelist content again using the previous script from [here](https://github.com/AudiusProject/audius-docker-compose/commit/e9d2bc0b8927693700a8042f2c4fe590c49868d6) but cleaned up a bit and made to work with the new flow. I tested delisting and udelisting users and tracks on stage CN12.
More straightforward command usage: `npm run creator:delist track 1,3,7`
vs the previous way: `npm run creator:delist -- -a add -l 1,3,7 -t track`

[CON-806] Add back updated delist script

---

creator-node/Caddyfile

Tested this on cn 8. It works, cache key is
```
ContentCache; hit; ttl=3585; key=GET-https-creatornode8.staging.audius.co-/content/QmZ5HcM7gHWAy4ermMV9U1szBm3CC85d97jbwZcxhm3sbD/150x150.jpg---bytes=0-1024
```
for https://creatornode8.staging.audius.co/content/QmZ5HcM7gHWAy4ermMV9U1szBm3CC85d97jbwZcxhm3sbD/150x150.jpg
Before this change, I was able to fetch from cache with a range request and trigger the partial image behavior. After this change, I can no longer.
We should still make this change for UX reasons https://github.com/AudiusProject/audius-protocol/pull/6028 but it doesn't work as written. Not sure why.

Add back caddy cache with range header in key

---

audius-cli

when auto upgrade happens the relay container gets pruned because it's launched pre-prune, this sets up the required plugins after the prune happens

launch plugins after prune

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.plugins.yml
discovery-provider/docker-compose.yml

Updates to v0.4.9, which is already out on foundation nodes. Other nodes keep reverting to this due to auto-upgrade. We'll need to sort out the proper sequencing of this when automating. Ignores identity because we haven't deployed v0.4.9 there yet.

Update to v0.4.9 except identity

---

common-services.yml
creator-node/Caddyfile
creator-node/docker-compose.yml
discovery-provider/Caddyfile
discovery-provider/docker-compose.yml

healthz will run on all nodes instead of just centrally.
Tested on staging, confirmed navigating to /healthz endpoint on local browser works, including subroutes.

[PROTO-1189] Add healthz to common services

---

common-services.yml

Since we don't have the build integrated into CI, I jumped the gun on suggesting we make the version use `TAG` by default.

Pin the healthz version

---

audius-cli
discovery-provider/docker-compose.plugins.yml

a number of stage nodes couldn't start up because trpc was not present for nginx
`nginx: [emerg] host not found in upstream "trpc" in /usr/local/openresty/conf/nginx.conf:274`
this adds the trpc demo as a plugin to satisfy that

add trpc demo as plugin

---

audius-cli
discovery-provider/docker-compose.plugins.yml
discovery-provider/docker-compose.yml

This PR moves relay into the main discovery compose since it's a "required" service and sets the precedent that all services in docker-compose.plugins.yml are optional. I think we can more cleanly achieve the latter using docker profiles.
Tested on stage dn2.

move relay into main compose file

---

audius-cli

Makes `audius-cli set-tag` disable auto-upgrade and print the command to re-enable with the cron. This allows us to test custom tags and revert more easily. I tested this on stage CN6 and confirmed that healthz reflects the updates accurately (removes the robot icon when auto-upgrade is disabled).

Make audius-cli set-tag disable auto-upgrade

---

discovery-provider/Caddyfile
discovery-provider/docker-compose.plugins.yml

Only runs as a plugin on DNs for now.
Tested on a stage node, verified dashboard was accessible at /dashboard

Add protocol dashboard as discovery plugin

---

audius-cli

Since we now hard-reset foundation to stage branch in order to get audius-docker-compose changes automatically deployed, auto-upgrade also needs to do a hard-reset instead of a simple pull. Operators should be doing `audius-cli set-tag <tag>` before doing any manual changes if they want to keep their work.
I tested this on prod CN5, and now it's able to auto-upgrade. One problem is that other nodes won't get this change because they're stuck unable to upgrade. They'll have to run `git fetch origin && git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)`.

Make auto-upgrade pull use a hard reset

---

audius-cli

Cherry-picks [this PR](https://github.com/AudiusProject/audius-docker-compose/pull/388) to main to hopefully avoid having to ask SPs to run a command to keep their git directory clean.

Make auto-upgrade pull use a hard reset (#388)

---

audius-cli

Tested by doing `audius-cli upgrade` and `watch docker ps -a` on a stage CN and DN. The tags for plugins get updated, but they don't needlessly recreate when the tag is unchanged.

Recreate plugins on launch

---

audius-cli

95% caused issues on stage DN2 last week. I think the node pulled somewhere before 95% disk util then couldn't successfully upgrade and pull after that because there was not enough space on the device. 
Prune slightly more aggressively - change threshold to 90%

Lower disk usage threshold when pruning in audius-cli

---

audius-cli
creator-node/Caddyfile
creator-node/docker-compose.plugins.yml
creator-node/docker-compose.yml
discovery-provider/Caddyfile
discovery-provider/docker-compose.plugins.yml
discovery-provider/docker-compose.yml

- Runs protocol dashboard in prod (dashboard is now a core service instead of a plugin)
- Makes stage use the same build as prod (static bundle served through Caddy instead of `vite`, which is only supposed to serve in a dev environment)
- Confirmed that this fixes the problem where the site doesn't load (blank screen) when going directly to a route (e.g., `/dashboard/#/services/content-node/12`)
- Checked out this branch on a stage CN and stage DN

[PROTO-1388] Run protocol dashboard on prod

---

audius-cli

Disabling cuz creator node plugins is empty which causes upgrade to exit.

Disable launching of CN plugins

---

discovery-provider/docker-compose.yml

This removes a mapping that forwards host.docker.internal to the hosts url, this messes up audius-d when working on mac. Exporters should be the only thing using this so since we removed though this change shouldn't have any effects.
tested on stage dn-3 by checking out this branch and launching discovery provider, on healthz it appears up and there doesn't seem to be any issues

rm hosts addition in server

---

creator-node/docker-compose.yml

Upgrades postgres from 11 to 15 for containerized Content Node dbs. The official docs say it's safe to upgrade directly to 16, but RDS only lets you go from 11 to 15, so maybe they know something I don't.
This automates the main steps of the upgrade:
1. Run the migration with both versions offline, using pg_upgrade (which does a lot for us)
2. Update `pg_hba.conf` so localhost can still connect - otherwise you get this error: `no pg_hba.conf entry for host, user "postgres", database, no encryption (SQLSTATE 28000)`
3. Re-build indexes (if we don't do this, query plans will be all messed up and cause slowness)
4. Drop the old data (I'll leave this part commented out on prod until after verification; we also have backups)
Note that this is only for mediorum to avoid upgrading too much at …

[PROTO-1458] Upgrade postgres on mediorum

---

creator-node/docker-compose.yml

Allows for empty PG11 and/or empty PG15. This is to fix a half-complete upgrade state, but we want it anyway for new nodes that have nothing to upgrade from (fresh slate).
I tested this on stage CN6 and confirmed with culturestake that it fixes one of their nodes with a corrupted database. My theory is that the cause of this was us pushing v0.5.30 and then v0.5.29 before doing v0.5.30 again. This caused an auto-upgrade in the middle of the postgres version upgrade.

Fix pg upgrade for corrupted mediorum dbs

---

discovery-provider/docker-compose.yml

Allows the indexer to be unhealthy for 2 hours (instead of 3 minutes) before restarting.

Bump indexer start_period to 2 hours

---

audius-cli
discovery-provider/docker-compose.yml

Fixes postgres upgrade for Discovery using a relative path to .env. When `audius-cli upgrade` is called via auto-upgrade (as opposed to manually), this made it set the postgres image version in `/home/ubuntu/.env` instead of `/home/ubuntu/audius-docker-compose/discovery-provider/.env`.

Fix using relative path to .env in pg upgrade

---

audius-cli

When the postgres upgrade runs into an error, it needs to clean up the delete-db container or else it might delete, which sometimes leaves the data folder stuck in pg 11 instead of pg 15. This simple change makes it more able to restart if it runs into an error.

Remove stale containers when pg upgrade fails

---

audius-cli
discovery-provider/docker-compose.yml

Makes `audius-cli upgrade` detect node type in a less error-prone and less confusing way:
1. creator-node only if creator-node/override.env exists and has `creatorNodeEndpoint` set
2. discovery-provider only if discovery-provider/override.env exists and has `audius_delegate_owner_wallet` set
3. identity-service only if identity-service/override.env is set and has `ethOwnerWallet` set
This also cleans up discovery containers that are running on identity and creator.

Improve node type detection and clean up DN containers

---

audius-cli

Expected behavior when running `audius-cli down` with no arguments is that all services and networks are removed. In the current state, the chain container and discprov network get left behind. This ensures everything is cleaned up.
tested on stage-discovery-5

Remove chain container when running 'audius-cli down'

---

ADVANCED_SETUP.md
README.md
creator-node/prod.env
creator-node/stage.env
setup.sh

Removes the ability to specify a custom database URL for content nodes, along with documentation about customizing the db URL for discovery nodes. I tested this on a staging content node to ensure the environment variable is unset in the `mediorum` container and that that service runs properly anyway.

[PROTO-1481] Remove option to configure hosted postgres

---

audius-cli

Ensures `audius-cli upgrade` always prunes, even if it encounters an error. I tested this on a stage CN and DN to make sure it runs as expected with the prune at the end, even when throwing a test exception:
```
git rev-parse HEAD
docker system prune --all --force --filter until=336h
Total reclaimed space: 0B
Traceback (most recent call last):
File "/usr/local/bin/audius-cli", line 1283, in <module>
cli(obj={})
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```

Always prune on audius-cli upgrade

---

creator-node/docker-compose.yml

Goes along with https://github.com/AudiusProject/audius-protocol/pull/6988 to limit mediorum's CPU and memory to slightly under the minimum Service Provider hardware requirements. Empirically, mediorum typically runs far below these limits - see htop from a prod creator node:

Limit mem and CPU on mediorum container

---

discovery-provider/Caddyfile
discovery-provider/docker-compose.yml

Introduces metabase as a plugin for running alongside a discovery node.
1. cd into `audius-docker-compose/discovery-provider`
2. run `docker compose --profile metabase up -d`
3. curl or go to `http://localhost` in your browser, this will show this json as you're hitting the `backend:5000` by default.
```
{
"error": [
"Route does not exist"
],
"success": false
}
```
4. install audius-cli
5. `python3 -m venv adc`, `source adc/bin/activate`
6. `cd ../`, `pip install -r requirements.txt`
7. `./audius-cli set-config discovery-provider ROOT_HOST metabase:3000`
8. `docker stop caddy`
9. `cd discovery-provider` + `docker compose --profile metabase up -d`
10. curl or go to `http://localhost` again and you should instead land on a metabase login screen (it may take a second to load, emulated image) …

Add metabase plugin

---

discovery-provider/Caddyfile
discovery-provider/docker-compose.yml

Run DDEX as a discovery plugin, accessible on the node at `/ddex`.
Merge after https://github.com/AudiusProject/audius-protocol/pull/6990.

Add ddex as plugin

---

discovery-provider/Caddyfile
discovery-provider/docker-compose.yml

Routes /ddex to a backend NodeJS server instead of serving frontend assets directly. Tested with the image from https://github.com/AudiusProject/audius-protocol/pull/7064.

[PROTO-1557] Make /ddex use container instead of pre-compiled dist

---

discovery-provider/Caddyfile

For the metabase plugin, /dashboard clobbers the namespace metabase uses for all its dashboards, thus making direct links not work. Generally speaking, we don't want people to override these configs, but in certain cases someone may want to.
This should have no impact to running nodes
*Instructions*
1. Set `NO_DASHBOARD=true` (or any non-empty value) in `discovery-provider/override.env`
2. audius-cli launch discovery-provider
Tested via `discovery-metabase` node that runs the plugin. Also confirmed that /healthz, /comms work as intended

Add conditional matchers for discovery Caddy directives

---

audius-cli
discovery-provider/docker-compose.yml

This will allow vector to process auto upgrade logs so we can see them in axiom.
https://github.com/AudiusProject/audius-protocol/compare/is-auto-upgrade-log?expand=1

Mount auto upgrade logs to vector container

---

discovery-provider/Caddyfile
discovery-provider/docker-compose.yml

Staging DDEX's web service runs at the root basename on a standalone node, https://audius-ddex.staging.audius.co/.
This is done by setting `ROOT_HOST=ddex-web:3000` in `discovery-provider/override.env`: https://github.com/AudiusProject/audius-docker-compose/blob/stage/discovery-provider/Caddyfile#L41
Tested on the audius-stage-ddex node.

DDEX web on standalone node

---

audius-cli
discovery-provider/docker-compose.yml

Based on auto upgrade logs, some nodes have chain containers that lose internet connection which is strange because the server has access to the internet otherwise. I suspect clearing the DB and recreating the chain container might fix these cases. 
Also recreate vector container on every upgrade to pick up new auto upgrade logs. Even if compose tag is not updated yet.

Recreate chain if unable to access internet

---

discovery-provider/docker-compose.yml

After merge:
* de-duplicate `nginx.conf` and `nginx_container.conf`
* remove openresty stuff from `start.sh`

Standalone openresty container

---

audius-cli

Since we don't have a reliable way to get SP ID in audius-cli without complexity (network/RPC checks against their endpoint env var), this PR rolls out a postgres upgrade for Discovery Nodes by:
1. Assigning a random number between 1 and 60 (only once - it's saved in override.env so it doesn't change on restart)
2. Upgrading if the number is < 10

[PROTO-1606] Rollout pg upgrade to ~1/6th of DNs

---

audius-cli

Recreate other containers as well. Adding --force-recreate vector only recreated the vector container.

Recreate other containers w change

---

audius-cli

Fixes strange behavior in the postgres upgrade on SPs. Logs show that they start upgrading again 1 second before completing, which shouldn't be possible with the current locks. Some possible causes that this PR aims to fix:
1. The next auto-upgrade task reads env before current one finishes setting the "upgrade complete" flag
2. Due to some SPs using tmpfs mounts for override.env, perhaps writing to this file doesn't work (or works differently). Using .env and tmp ~/.local may work more reliably
Note that this means I'll need to manually set the upgrade complete flag to true in the .env file of every node in order to prevent it from running again (it's currently set in the override.env).

Fix race conditions in upgrade for SPs

---

audius-cli

Rolls out the postgres upgrade to about half of Discovery Nodes. It's already rolled out to 1/6th successfully, including: culturestake3, culturestake9, culturestake14, culturestake17, and audius-nodes.com.
The only difference I see is that the db size is smaller. This is likely due to storage efficiency improvements in newer versions.

[PROTO-1606] Continue postgres rollout to ~half of DNs

---

audius-cli
discovery-provider/docker-compose.yml

Setting bootnodes here might help peer discovery. Tested on sandbox an stage.
https://ethereum.org/developers/docs/nodes-and-clients/bootnodes

Add bootnodes for peer discovery

---

audius-cli
discovery-provider/chain/config.cfg

There are 4 remaining unhealthy netherminde nodes. I suspect that this aggressive autohealing while a node syncs could have corrupted some data. I've seen cases where my sandbox disconnects with all peers because it has an old block that's empty while other nodes have the data. Re-syncing seems to resolve.
Turned on trace logging, verified my node would remove peers because of this discrepancy ^. Clearing clique db and re-syncing seems to have resolved.
Tested on sandbox.

Remove processing health check + recreate problem nodes

---

discovery-provider/docker-compose.yml

I believe this is causing issues on stage dn2 and potentially others
```
Do you want to continue? [y/N]: y
docker compose --project-directory /home/ubuntu/audius-docker-compose/discovery-provider pull
service "ddex-publisher" refers to undefined network ddex-network: invalid compose project
Traceback (most recent call last):
File "/usr/local/bin/audius-cli", line 1103, in <module>
cli(obj={})
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```

fix ddex network

---

audius-cli

On stage, passing in the stage.env to the chain container seemed to have changed the node address for some reason. Not sure why but reverting that for now. 
Also ensuring chain containers are re-synced once

Fix chain env and only recreate once

---

discovery-provider/chain/config.cfg

Removed in order to hopefully fix syncing issues, thinking constantly restarting while doing full sync could slow down / corrupt.
This is pretty important to keep for signer nodes though to prevent block production halts.

Add process check back

---

ddex/docker-compose.yml

Fixes DDEX ingester services failing to start on staging due to being unable to find env vars.

Pass env files to DDEX ingester apps

---

discovery-provider/docker-compose.yml

Updates Discovery because a failed image is blocking the latest changes from being automatically committed. I tested on a stage node to double-check that it can pull each image with this new tag and run successfully.

Update Discovery to latest

---

audius-cli

The server container depends on the chain but we can't codify this dependency because we want the chain on a different docker compose profile so that it won't get restarted during auto-upgrades.
Launching the chain before launching discovery provider helps with the race condition where [discprov server caches it's web3 endpoint before the chain is ready](https://github.com/AudiusProject/audius-protocol/blob/main/packages/discovery-provider/src/utils/web3_provider.py#L32).
Successfully deployed this change on stage discovery 3

Launch chain before launching the stack

---

ddex/docker-compose.yml

The DDEX publisher was reporting unhealthy because I removed its Express server, so this PR changes its health check to use `pgrep`. Also adds health checks to the other DDEX services. Tested on stage.

Update ddex health checks

---

audius-cli

Re-seeds discovery once unless `reseeded_exposed_postgres` env var is set to `true`.

Reseed exposed postgres (discovery + content)

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

These ports are used by the internal services. Publishing them via the `ports:` docker compose directive exposes them on the host level. This is unnecessary and presents potential security risks for nodes operating without a firewall.
Tested on stage dn5 and stage creator 12.

Remove all unnecessary published ports

---

discovery-provider/docker-compose.yml

Lately when trying to launch discovery provider it keeps prematurely failing because elasticsearch is unhealthy even though elasticsearch later becomes healthy on its own.

Increase healthcheck timeout on elasticsearch

---

discovery-provider/docker-compose.yml

Reverts AudiusProject/audius-docker-compose#495
this is causing merge conflicts on release and we'll need to hotfix it today, reverting now so we can do that and fix foundation + stage after the fact

Revert "Increase healthcheck timeout on elasticsearch"

---

discovery-provider/docker-compose.yml

Until we fix the divergence between stage, foundation, and main branches, this change has to be added in a way that doesn't touch the invisible forbidden void of merge conflict zone.

Add healthcheck start period in a way that doesn't cause merge conflicts

---

ddex/dev.env
ddex/docker-compose.yml
ddex/prod.env
ddex/stage.env

Changes DDEX to be compatible with recent changes in audius-protocol, including removing the "indexer" service and renaming the "-indexed" bucket to "-crawled."
DDEX now auto-upgrades on staging again. I also updated the buckets in S3 (deleted "indexed," created "crawled," and updated IAM policies).

Make DDEX work with protocol changes

---

ddex/docker-compose.yml

The `NETWORK` env var is "dev," "stage," or "prod," which doesn't match up with `NODE_ENV` being "production" or "development." So this PR changes DDEX to pass in `NETWORK` and let the app code set `NODE_ENV` based on that.
This is part of https://github.com/AudiusProject/audius-protocol/pull/8078.

Pass network instead of node_env to ddex

---

audius-cli

The set-tag feature will become an implementation detail as part of audius-d versioning. Auto-upgrade should remain enabled so that images can stay on the latest version of containers with a given tag. Setting the tag to a pinned version will be the de facto way of disabling auto-upgrade.
Tested by running local audius-d node on this branch with `set-tag` used by audius-ctl (see https://github.com/AudiusProject/audius-d/pull/100)

Keep tag when auto-upgrading

---

audius-cli
discovery-provider/seed.sh

This feature allows audius-d to automatically check if seeding is necessary when nodes are launched. This avoids having the extra seeding step during new node onboarding. The script simply checks if the database is below 2GB (stage db is ~25GB, prod is ~100GB, a fresh new database is only around 13MB).
Tested on stage dn5 (local database) and stage dn4 (remote database) - in both cases auto-seeding was correctly skipped because the database is already populated. Regular seeding should not be impacted.

Add auto-seed flag to audius-cli

---

audius-cli

If the audius-d wrapper container is shut down uncleanly, the services inside will auto-restart when it is spun up again. The internal containers will create their file volume mounts as empty directories. This will ensure those files are deleted if they are directories to avoid errors.
Tested with audius-d locally.

Remove empty chain spec directories

---

utilities/discovery-provider/healthChecks.js

Fix issue in checks on the /chain/peer endpoint
```
discoveryProviderEndpoint=https://discoveryprovider.audius.co npm run discovery:health
```
```
> sp-actions@1.0.0 discovery:health
> node discovery-provider/healthChecks.js
✓ Health check passed successfully
✓ IP forwarding check passed successfully
✓ websocket OK: wss://discoveryprovider.audius.co/comms/debug/ws
✓ acdc peering check
All checks passed!
```

Fix health check

---

discovery-provider/docker-compose.yml

these predate pedalboard and had a manual deploy process, this will make them more compatible with audius-d
tested on stage dn1 by registering both plugins

add uploads and rewards

---

discovery-provider/docker-compose.yml

Nodes regularly lock up from running out of memory while the chain is syncing. This may help prevent that from happening.
This was tested on dn1 tikilabs node.

[PROTO-1841] Add memory limit to chain container

---

creator-node/prod.env

The errors in prod aren't quite the same as stage. Turning this off and just turning on for foundation through override until bugs ironed out.

turn off discovery listens in prod

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

We're missing these logs for content nodes and audius-d migrated nodes.

[PROTO-1875] Mount auto-upgrade logs to vector container in audius-d compatible way

---

requirements.txt

web3 depends on the pgk_resources module from setuptools, but fails to include this in its dependencies.

Add setuptools as explicit dependency (because of web3)

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

This container almost never changes and will soon be absorbed into core.

Pin uptime container to 'current' tag

---

creator-node/docker-compose.yml
ddex/docker-compose.yml
discovery-provider/docker-compose.yml
identity-service/docker-compose.yml

Releases are now handled without updating git sha, so any nodes that don't have a tag set (e.g. legacy nodes) will default to current.

Default to 'current' tag when unset

---

creator-node/docker-compose.yml
discovery-provider/docker-compose.yml

`audius-ctl` is unable to create directories that do not already exist on the host.
for sake of ease, use a dir that exists on both node types ⚡ 
**TEST**
ran with the following audius-ctl config
```
network:
deployOn: mainnet
nodes:
<host>:
...
version: endl/corev
```
results in
```
$ ssh <host>
$ ls /var/k8s/bolt/
audius-mainnet-test2  uptime.db
```

Use pre-existing dir for comet persistent data

---

audius-cli

Possible that this file doesn't exist if the launch runs before a first auto upgrade.
Note sure why we haven't seen this before. Maybe a docker change?

Touch auto upgrade logfile on launch

---

creator-node/dev.env

docker-compose.yml file expects a .env for all network types, otherwise an error is thrown.

Dummy environment file for dev

---

.gitignore
utilities/claim/claim.js

Two things:
- Gas price not passed through or calculated. Recent eth craziness made this start causing TXs to not get mined and pile up. Had to manually set nonce, etc. to clear and then set this gasPrice to get things through
- Currently the wh redemption is not idempotent because it re-uses the tx has from the eth tx part. If, for whatever reason, the wormhole thing fails, that tx hash gets lost. Instead, memoize the tx hash in a file and keep that around to store failed tx for future retries. It would have been nice to just use the eth rpc to get the tx hash, but it's a big pain to look this up and there are no good log emits in that contract itself. We'd have to crawl up block by blocking looking for the right tx. PITA! Anyway, this works well
``` …
```

Fix init round gas price and idempotency

---

audius-cli
discovery-provider/docker-compose.yml

This service is no longer being used, and appears to be crashlooping.

Remove trpc

---

discovery-provider/Caddyfile

As part of creating a single lb to manage our discovery instances, I want to make fetching via ip also work in conjunction with the https hostname.
This is because we cannot have a cloudflare worker redirect requests to other cloudflare cached endpoints.

Accept direct requests via caddy

---

discovery-provider/docker-compose.yml

To handle more search traffic
Quick analysis shows most nodes have >32g avail.
Postgres could probably get a boost too

Up server & es memory limits

---

discovery-provider/Caddyfile

Caddy should ignore this if `audius_discprov_url_unproxied` doesn't resolve

Add unproxied host option
